/** Class strings shared by several components (the app's small design vocabulary). */
export const ui = {
  cardBox: "bg-surface border border-line rounded-card",
  card: "bg-surface border border-line rounded-card p-4",
  stack: "flex flex-col gap-3.5",
  muted: "text-muted text-sm",
  mutedXs: "text-muted text-xs",
  title: "text-xl font-bold leading-[1.15] tracking-tight text-balance",
  sub: "text-md font-semibold mb-2 text-balance",
  empty: "text-md font-semibold mb-1 text-balance",
  name: "text-md font-bold text-ink tabular-nums",
  pct: "text-lg font-semibold tabular-nums leading-[1.2]",
  lead: "font-semibold text-sm",
  dot: "inline-block size-2.5 rounded-full mr-2 bg-(--c-light) dark:bg-(--c-dark)",
  readerTop: "flex justify-between items-baseline gap-3",
  hero: "flex flex-row items-end gap-4",
  heroText: "min-w-0 flex-1 flex flex-col gap-1",
  field: "flex flex-col gap-1.5 font-medium text-sm",
  input:
    "text-md min-h-12 px-3 font-normal text-ink bg-page border border-line rounded-control focus-visible:outline-offset-0 focus-visible:border-accent aria-[invalid=true]:border-danger",
  fieldError: "text-danger font-medium text-sm",
  btn: "min-h-11 px-4 rounded-control border text-md font-semibold cursor-pointer enabled:active:scale-98 motion-reduce:enabled:active:scale-100 disabled:opacity-45 disabled:cursor-not-allowed",
  btnDefault: "border-line bg-surface text-ink",
  btnPrimary: "border-accent bg-accent text-on-accent",
  link: "min-h-11 bg-transparent border-0 text-muted text-sm underline cursor-pointer",
  toast: "px-3.5 py-3 rounded-control bg-track text-sm",
  toastError: "px-3.5 py-3 rounded-control text-sm bg-danger-tint border border-danger",
  list: "list-none",
  listItem: "flex justify-between items-center gap-3 py-2.5 border-t border-line first:border-t-0 text-sm",
  actions: "flex flex-wrap gap-2",
  chip: "self-start text-xs font-semibold px-2 py-0.5 rounded-full",
  chipLendo: "bg-accent text-on-accent",
  chipOther: "bg-track text-muted-strong",
  emptyState: "text-center py-8 px-4 flex flex-col items-center gap-2",
} as const;
